global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'website'
    scrape_interval: 15s
    static_config:
      - targets: ['website:80']

  - job_name: 'prometheus'
    scrape_interval: 15s
    static_config:
      - targets: ['localhost:9090']
   